spring:
  application:
    name: sample-code
  profiles:
    active: dev
# mvn clean package -P dev
# java -jar .\target\sample-code-0.0.1-SNAPSHOT.jar
server:
  port: 8888

# Health check
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  health: # config for EKS
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  prometheus:
    metrics:
      export:
        step: 5s
        enabled: true

# Logging
logging:
  level:
    root: INFO
    web: OFF
    org.springframework: INFO
    org.apache: OFF
    kafka: OFF