#server:
#  port: 8888
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/tayJava}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: localhost:29092

endpoint:
  confirmUser: http://localhost:${server.port}/api/v1/user/confirm

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: ${API_TITLE:DUMMY-API-TITLE}
    version: v1.0.0
    description: Sample Code
jwt:
  expiryHours: 3600000 # 1 hour
  expiryDays: 86400000 # 1 day
  secretKey: 297fb2dd8d41f7542cb6506ffef38b24011082a70aaaf09bdc0e619b5fca242b
  refreshKey: ClJMlDP88XazYN3/dtv16QggUW9Hj2eUN634idNOa1I=
  resetKey: 46dbe9f988aa45f86f5857ff1ba198ec35fd3e8bda60df10d309c91b59505ec4