server:
  port: 8888
spring:
  application:
    name: sample-code
  profiles:
    active: dev
# mvn clean package -P dev
# java -jar .\target\sample-code-0.0.1-SNAPSHOT.jar
# mvn clean install -DskipTests
# docker-compose up -d
# docker-compose down -v
# docker-compose ps -a
# docker-compose logs -tf

# Health check
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  prometheus:
    metrics:
      export:
        step: 5s
        enabled: true

logging:
  level:
    root: INFO
    web: OFF
    org.springframework: INFO
    org.apache: OFF
    kafka: OFF